repos:
  # Run lightweight checks first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: ['--autofix']
        exclude_types: [jupyter]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.11
    hooks:
      - id: uv-lock  # uv.lock always updated
        args: ['--python', 'python']
      # - id: uv-export   # uncomment if you want uv to generate requirements.txt file


  # Then run the heavier local formatters/linters
  - repo: local
    hooks:
      - id: ruff
        name: "Ruff Linter"
        entry: ruff
        language: system
        args: [check, --fix, --unsafe-fixes]
        types_or: [python, pyi, jupyter]
        pass_filenames: false

      - id: ruff-format
        name: "Ruff Formatter"
        entry: ruff
        language: system
        args: [format]
        types_or: [python, pyi, jupyter]
        pass_filenames: false

      - id: nbstripout
        name: "Clean Notebooks"
        entry: nbstripout
        language: system
        types: [jupyter]
        args: ["--drop-empty-cells"]

      - id: ty
        name: "ty type checks"
        entry: ty
        language: system
        args: [check]
        types_or: [python, pyi, jupyter]
        pass_filenames: false
